
host: 0.0.0.0
port: 4242

trackers:
  - type: progress

  - type: console

  - type: logfile
    config:
      logdir: logs
      suffix: .log

  - type: tensorboard
    config:
      log_dir: ''
      comment: ''
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''

  - type: slack
    config:
      token: null
      channel: '#nn_training'

  - type: sqlite
    config:
      database: db.sqlite
